### ISSUE TITLE
How to configure this environment on “Windows” ?

### ISSUE THREAD

**Issue by xukun-zhang** [SciKit-Surgery/scikit-surgerytutorial01#36]
Is this tutorial still updated ? I can 't configure the environment as described in the tutorial. So what do I need to pay attention to when configuring the environment on the Windows system, especially the configuration of PySide2 ?

**Comment by thompson318** [comment]
Hello, sorry for the slow response. Been away from the office. The tutorial should still work, although we haven't tested it since last November. It should be running PySide6 now but that should all be handled when you install scikit-surgeryutils. Can you give any more details on what errors you're getting?

**Comment by xukun-zhang** [comment]
Thank you very much for your answer, I have successfully run this tutorial. As you said, there are no errors when I use PySide6. Thank you again!

**Comment by xukun-zhang** [comment]
Thank you very much for your answer, I have successfully run this tutorial.
As you said, there are no errors when I use PySide6. Thank you again! 😁😁😁

Stephen Thompson ***@***.***> 于2023年10月17日周二 17:30写道：
